# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: tv_shows_development

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: tv_shows_test
